extends: airbnb
plugins:
  - react
  - jsx-a11y
  - import
env:
  browser: true
  node: true
rules:
  eol-last: off
  comma-dangle: off
  no-trailing-spaces: off
  max-len: off
  react/jsx-filename-extension: off
  react/require-default-props: off
  react/forbid-prop-types: off
  arrow-parens: off
  jsx-a11y/href-no-hash: off
  no-console: warn
  no-unused-vars: warn
  react/prefer-stateless-function: warn
  react/self-closing-comp: warn
  react/prop-types: warn